In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("national_covid19.csv")
df.head()

,date,cases_total,cases_pcr,cases_test_ab,discharges,deceases,icu,hospitalized
0,2020-02-21,3.0,3,NaN,NaN,NaN,NaN,NaN
1,2020-02-22,3.0,3,NaN,NaN,NaN,NaN,NaN
2,2020-02-23,3.0,3,NaN,NaN,NaN,NaN,NaN
3,2020-02-24,3.0,3,NaN,NaN,NaN,NaN,NaN
4,2020-02-25,4.0,4,NaN,NaN,NaN,NaN,NaN

In [3]:
cases_filter = (2_000 < df["cases_total"]) & (df["cases_total"] < 500_000) & (df["icu"] < 100_000)
cases_filter.any()

True

In [4]:
df.loc[cases_filter, ["cases_pcr", "discharges"]].head()

    cases_pcr  discharges
68     214387    108947.0
69     215663    112050.0
70     216965    114676.0
71     218394    117248.0
72     219277    118902.0

In [5]:
import requests

DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/reddit_all.json"
)

data = requests.get(DATA_URL).json()
print(type(data), len(data))

<class 'dict'> 2

In [6]:
posts = [p["data"] for p in data["data"]["children"]]

In [7]:
df_posts = pd.DataFrame.from_records(posts)
df_posts.head()

,approved_at_utc,subreddit,selftext,author_fullname,saved,mod_reason_title,gilded,clicked,title,link_flair_richtext,...,subreddit_subscribers,created_utc,num_crossposts,media,is_video,post_hint,preview,link_flair_template_id,crosspost_parent_list,crosspost_parent
0,None,wallstreetbets,,t2_amboe4pe,False,None,2,False,ðŸ”®WallStreetBets Predictions Tournament for Oct...,[],...,12952239,1.666916e+09,20,None,False,NaN,NaN,NaN,NaN,NaN
1,None,funny,,t2_2ta10nt2,False,None,0,False,The perfect ad...,[],...,44163467,1.666948e+09,5,"{'reddit_video': {'bitrate_kbps': 2400, 'fallb...",True,hosted:video,{'images': [{'source': {'url': 'https://extern...,85409106-7d50-11e7-a2b0-0ea49b7e8eb0,NaN,NaN
2,None,aww,,t2_b8tjnz2o,False,None,0,False,My own little house elf,[],...,32474395,1.666951e+09,1,None,False,image,{'images': [{'source': {'url': 'https://extern...,NaN,NaN,NaN
3,None,me_irl,,t2_g7uxrjse,False,None,0,False,Me_irl,[],...,6627159,1.666943e+09,8,None,False,image,{'images': [{'source': {'url': 'https://previe...,NaN,NaN,NaN
4,None,LeopardsAteMyFace,,t2_pvm3eesf,False,None,0,False,Ted Cruz is suprised to learn that delaying vo...,[],...,895163,1.666950e+09,0,None,False,image,{'images': [{'source': {'url': 'https://previe...,NaN,NaN,NaN

In [8]:
# Advanced groupby by a "floating" column (created on the fly)
(
    df_posts
    .groupby(df_posts["subreddit"].str.lower().str.contains("meme").rename("is_memes"))
    ["upvote_ratio"]
    .describe()
    .loc[:, "count":"std"]
)

          count      mean       std
is_memes
False      21.0  0.937619  0.037001
True        4.0  0.925000  0.054467